### ISSUE TITLE
GEM cursor problems on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [bbbradsmith/hatariB#14]
Hi again @bbbradsmith 

Sorry for opening so many issues.. I see this is in development now, so I think it's better to report those early while code is fresh!

I found out that, in fullscreen mode (in core options, monitor mode set to TV and hidden borders), GEM cursor is trapped in the upper half or the lower half of the screen sometimes when emulation starts, and only after moving the cursor around, it can be moved beyond that half of the screen.

In order to easily replicate the bug, put your host desktop cursor (the cursor in your native Linux system) to the upper border of the screen, and then launch the core from a terminal using the keyboard:

`retroarch -L ~/.config/retroarch/cores/hatarib.so` 

You will see the cursor is trapped in GEM.

You can get the same bug if you move the host cursor to the lower border of the screen before launching the core.

**Comment by bbbradsmith** [comment]
Does this only affect HatariB or does it affect other cores that use the mouse? To me this sounds like a RetroArch issue rather than something specific to the core.

I don't have a native linux system to test with though. On windows I can't seem to duplicate what you describe. There is a quirk that I can't move my mouse to the second monitor while RetroArch is focused, which isn't a fullscreen thing, but I know that's RetroArch's doing.

**Comment by vanfanel** [comment]
@bbbradsmith ooops, you're right, seems to affect other cores too (DOSBOX-CORE, for example).
How strange... Mouse functionality seemed rock-solid for me.

Well, only X11 seems to be affected, so who cares. Wayland works perfectly well on this regard, sorry for the false bug report!
