### ISSUE TITLE
Mouse control for on-screen keyboard

### ISSUE THREAD

**Issue by Pyman75** [bbbradsmith/hatariB#52]
The on-screen keyboard is displayed but it will not disappear and no keys work. I’m using 1Up arcade machine with latest hatarib build. Non - touchscreen. I use joystick and buttons to navigate on-screen keyboard. On-screen keyboards work ok with other cores. Atari800 and vice for example.

**Comment by bbbradsmith** [comment]
By default, L1 will raise the onscreen keyboard, the d-pad will move the cursor, and L1 will press a key. R1 will close the keyboard.

There is also one-shot mode, pressing R1 will raise the onscreen keyboard and pause the game. L1 will press a key and close the keyboard, or R1 will close without press instead.

The button used to raise the keyboard, or one-shot keyboard is separate from the other keyboard buttons. To customize the presses you can go to the core options, and scroll down to the RetroPad 1 category.

**Comment by Pyman75** [comment]
Retested. It’s still not working. Keyboard is displayed but buttons do not work.

**Comment by bbbradsmith** [comment]
I will need more explanation of what you are doing to understand what would be going on for you. Can you give me steps of how you set up your installation, open a game, then raise the keyboard where you have this problem? What buttons are you pressing?

Also, how are your buttons configured? What are the core settings in the RetroPad 1 category?

**Comment by Vweber73** [comment]
I think that what the OP means is that you can't use the Android device touch screen to hit directly the desired key, rather than having to scroll to the key with the pad. Indeed I also would like that. I just upgraded my Samsung Z fold 3 to a fold 6, which only supports the 64 bits version of Android, and Hataroid can't be installed on it. I really miss Hataroid on screen keyboard, with direct key presses, fully resizable, using all the available space, movable outside the ST screen area and with transparency to still see the screen when not possible.

It would be wonderful to have something like that on HatariB!

**Comment by bbbradsmith** [comment]
Okay, as a feature request I could understand it that way. This would have nothing specifically to do with Android if implemented.

So, essentially adding an option to allow a mouse/touch to operate the on-screen keyboard buttons.

Moving it outside the screen area is impossible through retroarch's interface. A core cannot draw anything outside the game's screen. Retroarch does have its own [separate way to make an onscreen keyboard interface](https://banjosmods.wordpress.com/2024/07/25/guides-retroarch-setting-up-a-keyboard-overlay/) which can maybe already do the things you're asking for, but it exists outside of what a core does.

Making it transparent is possible, but is a problem for this implementation which uses Hatari's own drawing library for the keys and text, and that library does not support transparency. I don't think I would consider this at this time.

**Comment by Vweber73** [comment]
Many thanks for your fast and detailed answer. I understand the issues at
stake. If you could already to the touch screen support that would be
wonderful!
Best regards

Le mer. 31 juil. 2024, 19:01, Brad Smith ***@***.***> a
écrit :

**Comment by bbbradsmith** [comment]
> You can see I press the on-screen keyboard activation button and press key "3" with same button and nothing happens.
Okay, so you're not talking about touch controls like Vweber73 mentioned.

So, I would need to know your mappings under Core Options > Retropad.

By default:
* L1 raises the keyboard. (regular mode)
* R1 raises the keyboard in one-shot mode (pauses emulation until a key is confirmed or cancelled).

Once raised, by default:
* On-Screen Keyboard Confirm is L1 (used to press/hold the key in, or in one-shot mode presses the key and resumes)
* On-Screen Keyboard Cancel is R1 (used to leave either keyboard mode without keypress).

So, if you pressed R1 twice it could look like what is seen in the video (R1 one shot mode, R1 cancel)

Alternatively if On-Screen Keyboard Cancel is mapped to the same button that raises the keyboard (e.g. if it's L1)  it would cancel instead of pressing a button in that mode too.

**Comment by Pyman75** [comment]
![image](https://github.com/user-attachments/assets/29c92217-2da7-4f6e-a7bc-a7856bdb2565)

**Comment by Pyman75** [comment]
> > You can see I press the on-screen keyboard activation button and press key "3" with same button and nothing happens.
> > Okay, so you're not talking about touch controls like Vweber73 mentioned.
> 
> So, I would need to know your mappings under Core Options > Retropad. I don't know which action your player-1 button maps to.
> 
> By default:
> 
> * L1 raises the keyboard. (regular mode)
> * R1 raises the keyboard in one-shot mode (pauses emulation until a key is confirmed or cancelled).
> 
> Once raised, by default:
> 
> * On-Screen Keyboard Confirm is L1 (used to press/hold the key in, or in one-shot mode presses the key and resumes)
> * On-Screen Keyboard Cancel is R1 (used to leave either keyboard mode without keypress).
> 
> So, if you pressed R1 twice it could look like what is seen in the video (R1 one shot mode, R1 cancel)
> 
> Alternatively if On-Screen Keyboard Cancel is mapped to the same button that raises the keyboard (e.g. if it's L1) it would cancel instead of pressing a button in that mode too. (You can find the configuration under Core Options > Retropad.)

![image](https://github.com/user-attachments/assets/9707a91a-05db-4c87-8021-91ee22e2b12f)

**Comment by bbbradsmith** [comment]
That is your RetroArch Input mappings, which wasn't the one I was referring too, but I think it indicates a problem that you have all of those mapped to "Button 108". I think this is most likely the issue you are having, multiple RetroArch inputs mapped from the same button.

The mappings I was actually asking about are in Quick Menu > Core Options > RetroPad, but it is likely these are in the default configuration I mentioned.

**Comment by Pyman75** [comment]
Many thanks for your help. I see where I missed the controls setup now 😊
